### PR TITLE
Assistant Tool code updates

### PR DESCRIPTION
**Pull request by manongjohn**
Ran beautification (clang-format) against the branch to clean up the code for files touched by the original PR only.

### CODE REVIEW

**Comment by blackwarthog** [comment]
Your qss are packed, but in opentoonz/master they are human-readable and contains comments.
Please tell me that changes in qss need we to do? I cannot understand it by diff, because a whole file was modified.

Beautification affects a lot of files that i haven't touched. I think will be better to create a dedicated PR for beautification to opentoonz/master.

**Comment by manongjohn** [comment]
The qss files are supposed to be packed so it is more efficient when loading.  Konero set up the Visual Code settings that way.

I will redo the beautification to only the files you touched.

**Comment by blackwarthog** [comment]
> The qss files are supposed to be packed so it is more efficient when loading.  Konero set up the Visual Code settings that way.

Work with packed qss and git is very hard. The best way is store both source qss with packed qss or pack qss while build.
But really qss became unpacked only in last commit, so i'll just replace files with your versions.

**Comment by manongjohn** [comment]
Should I just close this then?  

FYI, I looked through the files that were touched by the beautification.  Of the 89 files touched, 83 were updated by your PR and only 6 were not.  I can easily remove the 6 if you want.

I will be a little surprised if Shun doesn't require you to run beautification before he merges this.

**Comment by manongjohn** [comment]
Since you updated the qss files manually, I redid this PR to only be the beautification of the files you touched as part of the original PR.  Feel merge if you want.  If not, please just close it.

**Comment by blackwarthog** [comment]
Thanks a lot

**Pull request merged**
